maxNumCompThreads(1);
opts=struct('load_path','4c','nIncr',900,'Uy_end',0.5,'gamma',0.6, ...
 'E',29000,'nu',0.2,'ft',3,'GF',0.11,'k',10, ...
 'show_live',false,'save_all_increment_geometry',false,'show_mesh',false, ...
 'save_show_mesh',false,'print_stride',20,'maxIter',150, ...
 'use_line_search',true,'tol',1e-6,'strict_equilibrium',true, ...
 'maxLineSearch',12,'out_dir',pwd);
damage_static('Job-1',opts);
